name: big sure build

on:
  push:
    branches: [ master, bigsure-build ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: install deps
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install -f libffi gettext glib pkg-config autoconf automake pixman ninja
      - name: Build
        run: |
          mkdir -p build
          cd build && ../configure && make
